### ISSUE TITLE
traceback at the end "FileNotFoundError: [Errno 2] No such file or directory: '.../cpython-overhead/build/install-count-predefined/bin/python3.9'

### ISSUE THREAD

**Issue by cfbolz** [zq1997/cpython-overhead-evaluation#1]
Hi everyone!

Congratulations on your fantastic paper and thank you for making the source code available! Unfortunately I got an error at some point:

```
==================== instrumentation count: count-predefined ====================
deltablue:	warm[0.0s,ERROR]
2to3:	warm[0.0s,ERROR]
float:	warm[0.0s,ERROR]
json_dumps:	warm[0.0s,ERROR]
pathlib:	warm[0.0s,ERROR]
mdp:	warm[0.0s,ERROR]
pickle_pure_python:	warm[0.0s,ERROR]
python_startup_no_site:	warm[0.0s,ERROR]
regex_effbot:	warm[0.0s,ERROR]
spectral_norm:	warm[0.0s,ERROR]
sympy:	warm[0.0s,ERROR]
unpickle:	warm[0.0s,ERROR]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/util/count_helper.py", line 18, in _do_run
    benchmarks.run_bm(bm_meta, cpython, config.WARM_UP_DURATION)
  File "/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/util/benchmarks.py", line 33, in run_bm
    subprocess.check_call(
  File "/usr/lib/python3.9/subprocess.py", line 368, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/cfbolz/projects/misc/cpython-overhead/build/install-count-predefined/bin/python3.9'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/collect_data.py", line 16, in <module>
    count_helper.collect(config.D_COUNT_PREDEFINED)
  File "/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/util/count_helper.py", line 34, in collect
    pool.map(_do_run, args_list)
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/home/cfbolz/projects/misc/cpython-overhead/build/install-count-predefined/bin/python3.9'
```

And indeed there is no such file. Anything I can do to fix this?

**Comment by zq1997** [comment]
My mistake. Part of the code was outdated after the revision of the paper, but I did not delete it cleanly.
Maybe you can now try `git pull` and run the remaining command manually.
```
python3 collect_data.py
python3 estimate_confidence.py
python3 analyze_dwarf.py
find . -name study_\*.py -print0 | xargs -0L1 python3
```

**Comment by cfbolz** [comment]
thanks for the quick reply, and I really cannot stress enough how cool I find this work!

Did the push go through? my pull did nothing

**Comment by zq1997** [comment]
Some networks problem, it's pushed now.

**Comment by cfbolz** [comment]
ok, I get some more tracebacks:

```python3: can't open file '/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/estimate_confidence.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/analyze_dwarf.py", line 276, in <module>
    main()
  File "/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/analyze_dwarf.py", line 267, in main
    native_functions = find_native_func(elf_file, dwarf_info, addr2line)
  File "/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/analyze_dwarf.py", line 177, in find_native_func
    type_struct = StructType(dwarf_info, '../../cpython/Include/methodobject.h', 'PyMethodDef')
  File "/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/analyze_dwarf.py", line 130, in __init__
    for die in iter_die(dwarf_info):
  File "/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/analyze_dwarf.py", line 69, in iter_die
    for cu in dwarf_info.iter_CUs():
  File "/home/cfbolz/.local/lib/python3.9/site-packages/elftools/dwarf/dwarfinfo.py", line 353, in _parse_CUs_iter
    cu = self._cached_CU_at_offset(offset)
  File "/home/cfbolz/.local/lib/python3.9/site-packages/elftools/dwarf/dwarfinfo.py", line 383, in _cached_CU_at_offset
    cu = self._parse_CU_at_offset(offset)
  File "/home/cfbolz/.local/lib/python3.9/site-packages/elftools/dwarf/dwarfinfo.py", line 417, in _parse_CU_at_offset
    cu_structs = DWARFStructs(
  File "/home/cfbolz/.local/lib/python3.9/site-packages/elftools/dwarf/structs.py", line 92, in __init__
    assert address_size == 8 or address_size == 4
```

and later:

```
==================== post-process (with call graph): record-cycles-cg ====================
Traceback (most recent call last):
  File "/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/./study_opcodes.py", line 117, in <module>
    opcode_overhead_dist()
  File "/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/./study_opcodes.py", line 64, in opcode_overhead_dist
    dist, opcode_names = record_load_helper.load_opcode_dist_cg()
  File "/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/util/record_load_helper.py", line 230, in load_opcode_dist_cg
    dist = load_line_dist_cg(data_name)
  File "/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/util/saver.py", line 66, in new_func
    value = func_cache[key] = func(*args, **kwargs)
  File "/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/util/saver.py", line 46, in new_func
    result = func(*args, **kwargs)
  File "/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/util/record_load_helper.py", line 150, in load_line_dist_cg
    with open(config.CPY_FUNC_JSON) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/data/cpython-functions.json'
==================== post-process (with call graph): record-cycles-cg ====================
Traceback (most recent call last):
  File "/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/./study_name.py", line 150, in <module>
    name_access()
  File "/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/./study_name.py", line 76, in name_access
    cycle_dist, opcode_names = record_load_helper.load_opcode_dist_cg()
  File "/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/util/record_load_helper.py", line 230, in load_opcode_dist_cg
    dist = load_line_dist_cg(data_name)
  File "/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/util/saver.py", line 66, in new_func
    value = func_cache[key] = func(*args, **kwargs)
  File "/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/util/saver.py", line 46, in new_func
    result = func(*args, **kwargs)
  File "/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/util/record_load_helper.py", line 150, in load_line_dist_cg
    with open(config.CPY_FUNC_JSON) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/data/cpython-functions.json'

...

==================== post-process (with call graph): record-cycles-cg ====================
Traceback (most recent call last):
  File "/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/./study_dynamic.py", line 138, in <module>
    math_operator()
  File "/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/./study_dynamic.py", line 40, in math_operator
    dist = record_load_helper.load_line_dist_cg(config.D_RECORD_CYCLES_CG)
  File "/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/util/saver.py", line 66, in new_func
    value = func_cache[key] = func(*args, **kwargs)
  File "/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/util/saver.py", line 46, in new_func
    result = func(*args, **kwargs)
  File "/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/util/record_load_helper.py", line 150, in load_line_dist_cg
    with open(config.CPY_FUNC_JSON) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/cfbolz/projects/misc/cpython-overhead/cpython-overhead-evaluation/data/cpython-functions.json'
```

any ideas?

**Comment by zq1997** [comment]
The 3rd party tool `elftools` seems to crash. We just use it to read CPython's dwraf information to generate a list of all CPython native functions. I now include its result file `data/cpython-functions.json` into the repository, so no need to run it anymore.
```
find . -name study_\*.py -print0 | xargs -0L1 python3
```
Run the command directly and all the figures in the paper will be generated.

**Comment by cfbolz** [comment]
yeah, that finished, super cool! Is it worth it trying to re-run from a fresh checkout to see whether it goes through without manual interventions now?

**Comment by zq1997** [comment]
No need, the most critical sampling work was done yesterday. Today's crash is just something about post-processing.

**Comment by cfbolz** [comment]
Ok, then thanks for your help!
